//DerivedFiles/BibleVersificationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py on2011-01-17 20:46:57.284353
//
//  25BibleVersificationSystem loaded from the original XML file.
//

#include "BibleVersificationSystems_Tables.h"

