// DerivedFiles/BibleVersificationSystems_Tables.h
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py on 2010-12-27 16:02:18.948621
//

#ifndef BIBLEVERSIFICATIONSYSTEMS_Tables_h
#define BIBLEVERSIFICATIONSYSTEMS_Tables_h

