// DerivedFiles/BibleVersificationSystems_Tables.h
//
// This UTF-8 file was automatically generated by BibleChaptersVerses.py on 2010-12-16 18:05:04.948287
//

#ifndef BIBLEVERSIFICATIONSYSTEMS_Tables_h
#define BIBLEVERSIFICATIONSYSTEMS_Tables_h

