# DerivedFiles/BiblePunctuationSystems_Tables.py
#
# This UTF-8 file was automatically generated by BiblePunctuationSystems.py V0.01 2010-12-16 22:33:11.651440
#
#   1 BiblePunctuationSystem loaded from the original XML files.
#

from collections import OrderedDict


bookDataDict = {
  # Key is versificationSystemName
  # Fields are omittedVersesSystem

  "nSystem_English": {
    # Key is referenceAbbreviation
    # Fields are: id
    'booknameCase': 'ME',
    'chapterBridgeCharacter': '-',
    'verseBridgeCharacter': '-',
    'booknameLength': 'ME',
    'chapterVerseSeparator': ':',
    'punctuationAfterBookAbbreviation': '.',
    'spaceAllowedAfterBCS': 'E',
    'bookChapterSeparator': ' ',
    'chapterSeparator': ';',
    'bookSeparator': ';',
    'verseSeparator': ',',
  }, # end of nSystem_English (11 entries)

} # end of bookDataDict (1 systems)



# end of BiblePunctuationSystems_Tables.py