// DerivedFiles/BibleVersificationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BibleVersificationSystems.py on 2010-12-27 16:02:18.948621
//
//   25 BibleVersificationSystem loaded from the original XML file.
//

#include "BibleVersificationSystems_Tables.h"

