// DerivedFiles/BibleVersificationSystems_Tables.h
//
// This UTF-8 file was automatically generated by BibleChaptersVerses.py on 2010-12-22 15:22:05.524981
//

#ifndef BIBLEVERSIFICATIONSYSTEMS_Tables_h
#define BIBLEVERSIFICATIONSYSTEMS_Tables_h

