// DerivedFiles/BiblePunctuationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BiblePunctuationSystems.py V0.18 on 2011-01-17 20:46:59.261540
//
//   3 BiblePunctuationSystem loaded from the original XML file.
//

#include "BiblePunctuationSystems_Tables.h"


// English_brief
const static punctuationByRefEntry
 English_briefBookDataDict[12] = {
  // Fields (2) are const unsigned char referenceAbbreviation[3+1]; const int indexNumber;
  // Sorted by referenceAbbreviation
  {"bookBridgeCharacter", "-"},
  {"bookChapterSeparator", " "},
  {"bookSeparator", ";"},
  {"booknameCase", "ME"},
  {"booknameLength", "ME"},
  {"chapterBridgeCharacter", "-"},
  {"chapterSeparator", ";"},
  {"chapterVerseSeparator", ":"},
  {"punctuationAfterBookAbbreviation", ""},
  {"spaceAllowedAfterBCS", "E"},
  {"verseBridgeCharacter", "-"},
  {"verseSeparator", ","},
}; // English_briefBookDataDict (12 entries)


// Matigsalug
const static punctuationByRefEntry
 MatigsalugBookDataDict[12] = {
  // Fields (2) are const unsigned char referenceAbbreviation[3+1]; const int indexNumber;
  // Sorted by referenceAbbreviation
  {"bookBridgeCharacter", "–"},
  {"bookChapterSeparator", " "},
  {"bookSeparator", ";"},
  {"booknameCase", "ME"},
  {"booknameLength", "Unused"},
  {"chapterBridgeCharacter", "–"},
  {"chapterSeparator", ";"},
  {"chapterVerseSeparator", ":"},
  {"punctuationAfterBookAbbreviation", ""},
  {"spaceAllowedAfterBCS", "E"},
  {"verseBridgeCharacter", "-"},
  {"verseSeparator", ","},
}; // MatigsalugBookDataDict (12 entries)


// English
const static punctuationByRefEntry
 EnglishBookDataDict[12] = {
  // Fields (2) are const unsigned char referenceAbbreviation[3+1]; const int indexNumber;
  // Sorted by referenceAbbreviation
  {"bookBridgeCharacter", "-"},
  {"bookChapterSeparator", " "},
  {"bookSeparator", ";"},
  {"booknameCase", "ME"},
  {"booknameLength", "ME"},
  {"chapterBridgeCharacter", "-"},
  {"chapterSeparator", ";"},
  {"chapterVerseSeparator", ":"},
  {"punctuationAfterBookAbbreviation", "."},
  {"spaceAllowedAfterBCS", "E"},
  {"verseBridgeCharacter", "-"},
  {"verseSeparator", ","},
}; // EnglishBookDataDict (12 entries)


// Pointers to above data
const static tableEntry punctuationSystemTable[3] = {
  { "English_brief", English_briefBookDataDict, English_briefIndexNumberDataDict },
  { "Matigsalug", MatigsalugBookDataDict, MatigsalugIndexNumberDataDict },
  { "English", EnglishBookDataDict, EnglishIndexNumberDataDict },
}; // 3 entries

// end of BiblePunctuationSystems_Tables.c