# DerivedFiles/BiblePunctuationSystems_Tables.py
#
# This UTF-8 file was automatically generated by BiblePunctuationSystems.py V0.19 on 2011-01-18 10:43:22.979964
#
#   3 BiblePunctuationSystem loaded from the original XML files.
#

from collections import OrderedDict


bookDataDict = {
  # Key is versificationSystemName
  # Fields are omittedVersesSystem

  "English_brief": {
    # Key is referenceAbbreviation
    # Fields are: id
    'booknameCase': 'ME',
    'chapterBridgeCharacter': '-',
    'verseBridgeCharacter': '-',
    'booknameLength': 'ME',
    'spaceAllowedAfterBCS': 'E',
    'punctuationAfterBookAbbreviation': '',
    'chapterVerseSeparator': ':',
    'bookChapterSeparator': ' ',
    'chapterSeparator': ';',
    'bookBridgeCharacter': '-',
    'bookSeparator': ';',
    'verseSeparator': ',',
  }, # end of English_brief (12 entries)

  "Matigsalug": {
    # Key is referenceAbbreviation
    # Fields are: id
    'booknameCase': 'ME',
    'chapterBridgeCharacter': '–',
    'verseBridgeCharacter': '-',
    'booknameLength': 'Unused',
    'spaceAllowedAfterBCS': 'E',
    'punctuationAfterBookAbbreviation': '',
    'chapterVerseSeparator': ':',
    'bookChapterSeparator': ' ',
    'chapterSeparator': ';',
    'bookBridgeCharacter': '–',
    'bookSeparator': ';',
    'verseSeparator': ',',
  }, # end of Matigsalug (12 entries)

  "English": {
    # Key is referenceAbbreviation
    # Fields are: id
    'booknameCase': 'ME',
    'chapterBridgeCharacter': '-',
    'verseBridgeCharacter': '-',
    'booknameLength': 'ME',
    'spaceAllowedAfterBCS': 'E',
    'punctuationAfterBookAbbreviation': '.',
    'chapterVerseSeparator': ':',
    'bookChapterSeparator': ' ',
    'chapterSeparator': ';',
    'bookBridgeCharacter': '-',
    'bookSeparator': ';',
    'verseSeparator': ',',
  }, # end of English (12 entries)

} # end of bookDataDict (3 systems)



# end of BiblePunctuationSystems_Tables.py