# DerivedFiles/BibleOrganizationalSystems_Tables.py
#
# This UTF-8 file was automatically generated by BibleOrganizationalSystemsConverter.py V0.19 2011-01-17 20:47:01.855959
#
# Bible organizational systems list
#  Version: 0.14
#  Date: 2011-01-17
#
#   12 BibleOrganizationalSystems entries loaded from the original XML file.
dataDict = {
  # Key is extendedReferenceAbbreviation
  # Fields are: referenceAbbreviation, SBLAbbreviation, OSISAbbreviation, ParatextAbbreviation, ParatextNumberString, nameEnglish (comment only)
  'ASV_translation': {'languageCode': 'eng', 'name': ['American Standard Version'], 'referenceAbbreviation': 'ASV', 'publicationDate': '1901', 'versificationSystem': 'KJV', 'punctuationSystem': 'English', 'type': 'translation', 'bookOrderSystem': 'EuropeanProtestantBible', 'booksNamesSystem': 'eng_traditional'},
  'HEB_original': {'languageCode': 'hbo', 'name': ['Hebrew Scriptures'], 'referenceAbbreviation': 'HEB', 'booksNamesSystem': 'None', 'versificationSystem': 'Hebrew', 'punctuationSystem': 'None', 'type': 'original', 'bookOrderSystem': 'Hebrew'},
  'KJV-1611_edition': {'languageCode': 'eng', 'name': ['King James Version', 'Authorized Version'], 'usesText': 'KJV-1611_translation', 'referenceAbbreviation': 'KJV-1611', 'type': 'edition', 'publicationDate': '1611'},
  'KJV-1611_translation': {'languageCode': 'eng', 'name': ['King James Version', 'Authorized Version'], 'referenceAbbreviation': 'KJV-1611', 'publicationDate': '1611', 'versificationSystem': 'KJV', 'punctuationSystem': 'English', 'type': 'translation', 'bookOrderSystem': 'EuropeanProtestantBible', 'booksNamesSystem': 'eng_traditional'},
  'KJV-1769_edition': {'languageCode': 'eng', 'name': ['King James Version', 'Authorized Version'], 'usesText': 'KJV-1769_revision', 'referenceAbbreviation': 'KJV-1769', 'type': 'edition', 'publicationDate': '1769'},
  'KJV-1769_revision': {'languageCode': 'eng', 'name': ['King James Version', 'Authorized Version'], 'derivedFrom': 'KJV-1611', 'referenceAbbreviation': 'KJV-1769', 'publicationDate': '1769', 'versificationSystem': 'KJV', 'punctuationSystem': 'English', 'type': 'revision', 'bookOrderSystem': 'EuropeanProtestantBible', 'booksNamesSystem': 'eng_traditional'},
  'LXX_translation': {'languageCode': 'grc', 'name': ['Septuagint', 'LXX'], 'referenceAbbreviation': 'LXX', 'publicationDate': '300 BC', 'versificationSystem': 'Septuagint', 'punctuationSystem': 'None', 'type': 'translation', 'bookOrderSystem': 'Septuagint', 'booksNamesSystem': 'None'},
  'MBT_edition': {'languageCode': 'mbt', 'name': ['Matigsalug NT+'], 'usesText': 'MBT_translation', 'referenceAbbreviation': 'MBT', 'type': 'edition', 'publicationDate': '2011'},
  'MBT_translation': {'languageCode': 'mbt', 'name': ['Matigsalug'], 'referenceAbbreviation': 'MBT', 'publicationDate': '2010', 'versificationSystem': 'RSV52', 'punctuationSystem': 'Matigsalug', 'type': 'translation', 'bookOrderSystem': 'EuropeanProtestantBible', 'booksNamesSystem': 'mbt'},
  'NTG_original': {'languageCode': 'grc', 'name': ['Greek Scriptures'], 'referenceAbbreviation': 'NTG', 'booksNamesSystem': 'None', 'versificationSystem': 'KJV', 'punctuationSystem': 'None', 'type': 'original', 'bookOrderSystem': 'Unknown'},
  'RSV52_revision': {'languageCode': 'eng', 'name': ['Revised Standard Version'], 'derivedFrom': 'ASV', 'referenceAbbreviation': 'RSV52', 'publicationDate': '1952', 'versificationSystem': 'RSV52', 'punctuationSystem': 'English', 'type': 'revision', 'bookOrderSystem': 'EuropeanProtestantBible', 'booksNamesSystem': 'eng_traditional'},
  'RSV_edition': {'languageCode': 'eng', 'name': ['Revised Standard Version'], 'usesText': 'RSV52', 'referenceAbbreviation': 'RSV', 'type': 'edition', 'publicationDate': '1952'},
}
# end of dataDict

indexDict = {
  # Key is referenceAbbreviation
  # Fields are: id, SBLAbbreviation, OSISAbbreviation, ParatextAbbreviation, ParatextNumberString, nameEnglish (comment only)
  'ASV': ['ASV_translation'],
  'HEB': ['HEB_original'],
  'KJV-1611': ['KJV-1611_translation', 'KJV-1611_edition'],
  'KJV-1769': ['KJV-1769_revision', 'KJV-1769_edition'],
  'LXX': ['LXX_translation'],
  'MBT': ['MBT_translation', 'MBT_edition'],
  'NTG': ['NTG_original'],
  'RSV': ['RSV_edition'],
  'RSV52': ['RSV52_revision'],
}
# end of indexDict

combinedIndexDict = {
  # Key is referenceAbbreviation
  # Fields are: id, SBLAbbreviation, OSISAbbreviation, ParatextAbbreviation, ParatextNumberString, nameEnglish (comment only)
  'ASV': ['ASV_translation'],
  'ASV_translation': ['ASV_translation'],
  'HEB': ['HEB_original'],
  'HEB_original': ['HEB_original'],
  'KJV-1611': ['KJV-1611_translation', 'KJV-1611_edition'],
  'KJV-1611_edition': ['KJV-1611_edition'],
  'KJV-1611_translation': ['KJV-1611_translation'],
  'KJV-1769': ['KJV-1769_revision', 'KJV-1769_edition'],
  'KJV-1769_edition': ['KJV-1769_edition'],
  'KJV-1769_revision': ['KJV-1769_revision'],
  'LXX': ['LXX_translation'],
  'LXX_translation': ['LXX_translation'],
  'MBT': ['MBT_translation', 'MBT_edition'],
  'MBT_edition': ['MBT_edition'],
  'MBT_translation': ['MBT_translation'],
  'NTG': ['NTG_original'],
  'NTG_original': ['NTG_original'],
  'RSV': ['RSV_edition'],
  'RSV52': ['RSV52_revision'],
  'RSV52_revision': ['RSV52_revision'],
  'RSV_edition': ['RSV_edition'],
}
# end of combinedIndexDict

