// DerivedFiles/BiblePunctuationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BiblePunctuationSystems.py on 2010-12-16 22:33:11.655058
//
//   1 BiblePunctuationSystem loaded from the original XML file.
//

#include "BiblePunctuationSystems_Tables.h"


// nSystem_English
const static punctuationByRefEntry
 nSystem_EnglishBookDataDict[11] = {
  // Fields (2) are const unsigned char referenceAbbreviation[3+1]; const int indexNumber;
  // Sorted by referenceAbbreviation
  {"bookChapterSeparator", " "},
  {"bookSeparator", ";"},
  {"booknameCase", "ME"},
  {"booknameLength", "ME"},
  {"chapterBridgeCharacter", "-"},
  {"chapterSeparator", ";"},
  {"chapterVerseSeparator", ":"},
  {"punctuationAfterBookAbbreviation", "."},
  {"spaceAllowedAfterBCS", "E"},
  {"verseBridgeCharacter", "-"},
  {"verseSeparator", ","},
}; // nSystem_EnglishBookDataDict (11 entries)


// Pointers to above data
const static tableEntry punctuationSystemTable[1] = {
  { "nSystem_English", nSystem_EnglishBookDataDict, nSystem_EnglishIndexNumberDataDict },
}; // 1 entries

// end of BiblePunctuationSystems_Tables.c