// DerivedFiles/BibleVersificationSystems_Tables.c
//
// This UTF-8 file was automatically generated by BibleChaptersVerses.py on 2010-12-16 18:05:04.948287
//
//   26 BibleVersificationSystem loaded from the original XML file.
//

#include "BibleVersificationSystems_Tables.h"

